name: CI - Test and Verify

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # This ensures your build environment matches the Lambda environment
    container:
      image: amazonlinux:2023

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install HEIC Dependencies
        # Amazon Linux uses 'dnf' instead of 'apt-get'
        run: |
          dnf install -y golang-1.25 libde265-devel gcc

      - name: Run Tests
        env:
          GOARCH: amd64
          GOOS: linux
          CGO_ENABLED: 1
        run: go test -v ./...

      - name: Verify Build
        env:
          GOARCH: amd64
          GOOS: linux
          CGO_ENABLED: 1
#        run: go build -o bootstrap ./cmd/photo-thumbnail
        run: go build -o bootstrap -ldflags '-extldflags "-static"' ./cmd/photo-thumbnail